server.port: 8888

spring:
  application.name: gateway
  config.zookeeper.connect-string: "localhost:2181"
  zipkin.base-url: "http://localhost:9411"
  sleuth.sampler.probability: 1.0
  redis:
    host: localhost
    port: 6379
  cloud:
    gateway:
      routes:
        - id: menu-route
          uri: lb://binarytea
          predicates:
            - Path=/menu/**
          filters:
            - SecureHeaders
#            - name: RequestRateLimiter
#              args:
#                keyResolver: "#{@pathKeyResolver}"
#                redis-rate-limiter.replenishRate: 1
#                redis-rate-limiter.burstCapacity: 30
#                redis-rate-limiter.requestedTokens: 30
            - FallbackHeaders
            - name: CircuitBreaker
              args:
                name: menu-cb
                fallbackUri: forward:/fallback
                statusCodes:
                  - INTERNAL_SERVER_ERROR
        - id: order-route
          uri: lb://binarytea
          predicates:
            - name: Path
              args:
                patterns: /order/**
          filters:
            - name: RemoveRequestHeader
              args:
                name: User-Agent
        - id: token-route
          uri: http://localhost:8080
          predicates:
            - Path=/token
          filters:
            - PreserveHostHeader
            - name: Retry
              args:
                retries: 5
                methods: POST
#                series: CLIENT_ERROR
                backoff:
                  firstBackoff: 10ms
                  maxBackoff: 50ms
                  basedOnPreviousValue: false
          metadata:
            connect-timeout: 500
            response-timeout: 500
        - id: new-token-route
          uri: lb://binarytea
          predicates:
            - Path=/binarytea/token
            - Method=POST
          filters:
            - StripPrefix=1
      httpclient:
        compression: true
        connect-timeout: 1000
        response-timeout: 3s
      default-filters:
        - SecureHeaders

management:
  endpoint.gateway.enabled: true
  endpoints.web.exposure.include: "*"
